### ISSUE TITLE
Add setup.py, setup.sh, README.md and requirements.txt files

### ISSUE THREAD

**Issue by henson-tmp** [matiflaszcz/beer_app#2]

**Comment by mstopa** [comment]
@matiflaszcz wprowadź proszę następujące poprawki:
- utwórz branch develop i na nim wprowadź poprawki. na koniec zrób PRa i dodaj mnie proszę w assignee
- W README dodaj sekcje `setup` i `usage`. W `setup` opisz, jak przygotować Twoją aplikację do pracy, a w `usage` wrzuć przykładowe wywołanie. Do obejrzenia: https://www.youtube.com/watch?v=Uzpn2rmx_Fg
- rozwiąż buga:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```
- `import webbrowser` - unused import
- skasuj # webbrowser.open('https://api.punkapi.com/v2/beers')
- Usuń polskie nazwy zmiennych
- Obejrzyj filmik https://www.youtube.com/watch?v=fFY5103p5-c i popraw czystość kodu

**Comment by henson-tmp** [comment]
solved
